name: python-client

on: 
  push: 
    paths: 
      - 'python-client/**'
      - '.github/workflows/python-client.yml'
    branches:
      - main
  pull_request: 
    paths: 
      - 'python-client/**'
      - '.github/workflows/python-client.yml'

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        shell: bash
        working-directory: python-client

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"

      - name: Install pinned dependencies
        run: |
          pip install -r requirements.txt

      - name: Install
        run: |
          pip install -e .

      - name: Install Annotate Test Results Plugin
        run: pip install pytest-github-actions-annotate-failures

      - name: Test
        run: |
          pytest
      
      - name: Package 📦
        if: github.ref == 'refs/heads/main'
        run: |
          python setup.py sdist
        
      - name: Publish 📦 to PyPI
        if: github.ref == 'refs/heads/main'
        uses: pypa/gh-action-pypi-publish@release/v1.5
        with:
          password: ${{ secrets.NTSJENKINS_PYPI }}
          packages_dir: python-client/dist
